import Head from "next/head";

import {AiFillTwiterCircle, AiFillLinkedIn, AiFillYoutube} from 'react-icons/ai'

export default function Home() {
  return (
    <div>
        <Head>
          <title>Afonso Campos Port_Fólio</title>
          <meta name='description' content='Generated by crea'></meta>
          <link rel="icon" href="/favicon.ico"/>
        </Head>

        <main className="bg-white px-10">
          <section className="min-h-screen">
            <nav className="py-10 mb-12 flex justify-between">
              <h1 className="text-xl" font-burtons>developedBynizzo</h1>
              <ul className="flex items-center">
                <li>?</li>
                <li><a className="bg-gradient-to-r  from-cyan-500 text-white px-4 py-2 rounded-md ml-8" href="#">Resume</a></li>
              </ul>
            </nav>
            <div>
              <h2>Afonso Campos</h2>
              <h3>Developer</h3>
              <p><em>A cool guy learning how to code</em></p>
            </div>
            <div>

            </div>
          </section>
        </main>


    <main></main>
    </div>

  );

}
